language: python

sudo: true
fast_finish: true

matrix:
  include:
    - python: 3.10
    - python: 3.11
    - python: 3.12

install:
  # Use modern packaging approach
  - pip install --upgrade pip build
  # Install the package directly (pyproject.toml will be used)
  - pip install .

script:
  - nosetests

after_success:
  - coveralls

branches:
  only:
    - main

notifications:
  slack: tradologics:HcnS6XusfcuS02waQPCG18oc
  webhooks:
    urls:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
